name: mages
base: core22
version: "0.0.0"
summary: Matrix client with a tray notifier.
description: |
  Matrix chat client written in kotlin and rust.

grade: stable
confinement: strict

apps:
  mages:
    command: mages.AppImage
    plugs:
      - network
      - network-bind
      - pulseaudio
      - wayland
      - x11
      - home

parts:
  mages:
    plugin: dump
    source: ./builds/
    source-type: local
    organize:
      'mages.AppImage': mages.AppImage
    override-build: |
      craftctl default
      chmod +x $CRAFT_PART_INSTALL/mages.AppImage
