name: mages
base: core22
version: "0.0.0"
summary: Matrix client with a tray notifier.
description: |
  Matrix chat client written in kotlin and rust.

grade: stable
confinement: strict

apps:
  mages:
    command: bin/mages
    plugs:
      - network
      - network-bind
      - pulseaudio
      - wayland
      - x11
      - home

parts:
  mages:
    plugin: dump
    source: https://github.com/mlm-games/mages/releases/download/VERSION_PLACEHOLDER/mages-VERSION_PLACEHOLDER-x86_64.AppImage
    source-type: http
    organize:
      'mages-*.AppImage': bin/mages.AppImage
    override-build: |
      mkdir -p $SNAP/bin
      cp mages-*.AppImage $SNAP/bin/mages.AppImage
      cat > $SNAP/bin/mages << 'EOF'
      #!/bin/sh
      exec "$SNAP/bin/mages.AppImage" "$@"
      EOF
      chmod +x $SNAP/bin/mages $SNAP/bin/mages.AppImage
    build-packages:
      - ca-certificates
